### ISSUE TITLE
(Feature) Support Lead Acid Batterys (mostly 6V/12V)

### ISSUE THREAD

**Issue by designer2k2** [ginbot86/DingoCharge-Shizuku#16]
Hello,
would it be possible to support lead acid battery’s?

Use case to charge a car/motorcycle battery with it :-)  Or at least top it up

Depending on the used type it would require 14,4V or 14,8V for 12V battery’s. 
There are some articles on how to charge a car battery: 
- https://batteryuniversity.com/article/bu-403-charging-lead-acid
- https://www.power-sonic.com/blog/how-to-charge-a-lead-acid-battery/

**Comment by ginbot86** [comment]
Support for lead-acid batteries is planned but not formally implemented yet. I've personally used DingoCharge as a float charger by using 3.4V/cell in 4S configuration to get 13.6V for a 12V battery. You can use 3.4V/cell and 2S for a 6V lead-acid and set the termination rate to zero.

**Comment by ginbot86** [comment]
Closing the issue for now; see the wiki article for the alternative chemistry charging guide: https://github.com/ginbot86/DingoCharge-Shizuku/wiki/Charging-Non%E2%80%90Lithium-Battery-Chemistries-with-DingoCharge
