### ISSUE TITLE
(Feature Request) Please add support for NiMH batteries and battery packs.

### ISSUE THREAD

**Issue by JimKnopfIoT** [ginbot86/DingoCharge-Shizuku#17]
I sometimes have NiMH battery packs. Actually 3x 1,2 V = 3,6V/2700mAh from a Toniebox which i want to test/charge with logging function. Would be usefull if you can add support for NiMH batteries/packs.

**Comment by ginbot86** [comment]
Work is still ongoing to fully support Ni-MH with -dV/0dV termination, but DingoCharge in its current state, with changes to some advanced settings and/or external temperature-sensing circuitry, can charge Ni-MH in slow mode (0.1C for 16 hours), or fast mode (1-1.5C until temperature hits 40-45 degC). Refer to this wiki page for information on how to do this: https://github.com/ginbot86/DingoCharge-Shizuku/wiki/Charging-Non%E2%80%90Lithium-Battery-Chemistries-with-DingoCharge

If you don't want to source/solder a temperature sensor cable, I recommend using the slow-charge method. For your 3.6V/2700mAh Ni-MH pack, set the cells to 2S, voltage to 2.55V/cell (5.1V total), current to 0.270A, termination rate to 0.99C. From the main menu, go to Advanced -> Time Limit -> Set Time Limit... -> 16h. Once these settings are applied, select Start Charging in the main menu and follow the directions in the program.

**Comment by ginbot86** [comment]
Closing the issue for now, much like issue 16: https://github.com/ginbot86/DingoCharge-Shizuku/issues/16 but will update when official Ni-MH/Ni-Cd support is added.
